### PR TITLE
Add a regression test mode

### PR DESCRIPTION
**Pull request by achow101**
Add a mode to work with the Regression Test network with Bitcoin Core. This is useful for doing tests which I am in the process of writing.

Mining to an address in Armory can be done with the `generatetoaddress` rpc from PR https://github.com/bitcoin/bitcoin/pull/7671 that I submitted to Bitcoin Core

## Issues
 - It doesn't warn when both testnet and regtest are used simultaneously, it just exits the program
 - Examining Coinbase transactions doesn't work. This isn't specific to Regtest, but rather the most obvious on Regtest. See #23

### CODE REVIEW

**Comment by goatpig** [comment]
This is too much fresh code for this release. I'll review and merge this after 0.94 is out.

**Comment by achow101** [comment]
rebased onto master, added the gui warning when both regtest and testnet are in use

**Comment by achow101** [comment]
This is also necessary to test segwit since segnet is now deprecated and testnet is too unpredictable.

**Comment by achow101** [comment]
merged as part of #47 in commit a1a6a2930b9c535098819e64d87563f3663638ce

**Pull request closed without merging**
