### PR TITLE
Personnel page update

### PR DESCRIPTION
**Pull request by droark**
- Update the personnel.
- Update the libraries used by Armory and the tools used to build Armory.
- Minor grammatical cleanup.

### CODE REVIEW

**Comment by droark** [comment]
@achow101 @goatpig - Slowly updating the website. Figured I'd start with the personnel. Is what I wrote okay?

**Comment by achow101** [comment]
LGTM

While you're at it, can you add links to everyone's githubs?

**Comment by droark** [comment]
Sure. I'll do a fixup in a bit.

**Comment by achow101** [comment]
ACK 31479faa755e67ea50672ca3586ab703fd069d4e

**Pull request closed without merging**
