### PR TITLE
Create transactions with RBF

### PR DESCRIPTION
**Pull request by achow101**
Enables RBF transaction sending in expert mode.  It's just #42 rebased onto dev and pr'ed into dev.

### CODE REVIEW

**Comment by droark** [comment]
Hey. Can we just this rebased? I'd love to see RBF supported.

**Comment by achow101** [comment]
Considering the changes that have been done in dev since this PR was made, I don't know whether this will work at all. I will try.

**Comment by goatpig** [comment]
For RBF to work what you really need is the DB filtering and serving them. That's the complicated part. 

This PR will let you create RBF but will lack the code to let you actually replace a ZC.

**Comment by goatpig** [comment]
Don't bother imo. I have GUI place holders for RBF and CPFP. You can see those in the new coin control GUI if you are curious. Gonna have to do the DB side though before this has a change.

**Pull request closed without merging**
