### PR TITLE
Fix build instructions for Linux

### PR DESCRIPTION
**Pull request by david-yam**
Fix build instructions for Linux.

### CODE REVIEW

**Comment by droark** [comment]
ACK

**Comment by goatpig** [comment]
Don't PR to master please, rebase to testing for merge.

**Comment by nimbosa** [comment]
@david-yam, this was fixed in testing branch as of commit d2d335450ad4aeb53fea7d5490c6112ba6aada63 (July 3), right?

**Comment by david-yam** [comment]
@nimbosa, yes. 

@goatpig , noted not to PR to master.  Sorry for this.

**Pull request closed without merging**
