### PR TITLE
restore fixed size socket buffer behavior with windows compatible send()

### PR DESCRIPTION
**Pull request by jameshilliard**
This restores the behavior reverted in #631 for non-windows systems

### CODE REVIEW

**Comment by jameshilliard** [comment]
I should maybe add that the way `send()` is being used here does not seem to be correct and is likely to not work on larger message sizes(which was the reason I had rewritten it in the first place). Generally socket reading/writing should always be done within a loop like my `write()` loop here. I don't have a windows development setup however to test what's happening there.

**Comment by jameshilliard** [comment]
I replaced `write()` with `send()` which should allow this to also be used on windows

**Comment by jameshilliard** [comment]
For some more background, just doing `send()` outside a retry loop is broken because `send()` is not guaranteed to write the entire payload, you must check the return value for the actual number of bytes that were written to the socket and then continue to call `send()` with the remaining bytes until the entire payload has been written. Now doing a single `send()` outside a retry loop may work fine for smaller payloads most of the time but this is not guaranteed and will cause the payload to fail to get fully written in many cases.

**Comment by jameshilliard** [comment]
Also I updated the python side to always read in 4096 byte chunks which should match the cpp side write size for better performance.

**Comment by jameshilliard** [comment]
Note that using a 4096 byte `recv()` should not cause problems on small payloads as 4096 is simply the maximum chunk bytes we will receive per `recv()` call, it does not specify the minimum amount of bytes to read as that can be anything effectively up to the max `recv()` bytes.

**Comment by jameshilliard** [comment]
I think there's more areas in `SocketObject.cpp` that have broken socket handling code. I'd recommend auditing all read/write calls to ensure that they are always done within a retry loop that checks the return value for the actual amount of bytes written, failing to do this will result in strange freezing issues.

**Comment by pavel-kokolemin** [comment]
> For some more background, just doing `send()` outside a retry loop is broken because `send()` is not guaranteed to write the entire payload...

Could you please show some reference to this? From what I see it's OK to send in one call.

https://linux.die.net/man/3/send :

> If space is not available at the sending socket to hold the message to be transmitted, and the socket file descriptor does not have O_NONBLOCK set, send() shall block until space is available.

https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-send :

> If no buffer space is available within the transport system to hold the data to be transmitted, send will block unless the socket has been placed in nonblocking mode.

**Comment by jameshilliard** [comment]
From what I can tell we are setting `O_NONBLOCK` for these sockets.

>  On nonblocking stream oriented sockets, the number of bytes written can be between 1 and the requested length, depending on buffer availability on both the client and server computers.

**Comment by pavel-kokolemin** [comment]
For non-blocking sockets it does not make sense to call `send` in a loop as it will just work as a busy-waiting blocking call.

**Comment by jameshilliard** [comment]
From my understanding when running in non-blocking mode send doesn't block even if the payload hasn't been fully sent so because of that we need to use a loop to keep calling send until the payload is fully sent.

**Comment by goatpig** [comment]
There seems to be some confusion here.

There are 2 socket classes in Armory, SimpleSocket and PersistentSocket. SimpleSocket is used for the Core RPC (1 time use sockets), and meant to be initialized as blocking. It also differs from PersistantSocket in that it doesn't manage its own thread.

PersistentSocket is the non blocking, managed socket code. It has a dedicated implementation for unix and windows and implements the non blocking model correctly. You can look at the implementation here:

https://github.com/goatpig/BitcoinArmory/blob/dev/cppForSwig/SocketObject.cpp#L259
https://github.com/goatpig/BitcoinArmory/blob/dev/cppForSwig/SocketObject.cpp#L413

If you want to move the CppBridge code to a non blocking socket, please use PersistentSocket instead of modifying SimpleSocket, which is meant for quick and dirty blocking operations.

**Comment by goatpig** [comment]
Implemented async socketing for CppBridge in this PR (https://github.com/goatpig/BitcoinArmory/commit/3027c588c2f3486f1914666587a44083fd18b7c8), this should fix the issue. Closing this PR for now.

**Pull request closed without merging**
