### PR TITLE
Indicates whether transactions are Opt In RBF

### PR DESCRIPTION
**Pull request by achow101**
Transactions that opt in to RBF are now marked as so and the extra information is shown in the transaction details in the GUI.

### CODE REVIEW

**Comment by goatpig** [comment]
Give me a day to review this thoroughly. I went over it quickly and I'm not sure I saw it handling an actual replacement, only flagging transactions. 

Ideally only zero conf tx should be processed for RBF flagging (any entry in the ledger where the confirmation count is at 0). Do you mind making sure that's in place, and if not, adding it?

**Comment by achow101** [comment]
Right now it doesn't handle replacements, only flagging any transaction that indicates replacement.

I will add it in to only flag it if it is 0-conf.

**Comment by achow101** [comment]
I'm not entirely sure where to add the code for handling replacement. Would it be in the c++ section?

**Comment by goatpig** [comment]
Yes that will require a lot of C++ handling in the ZeroConf container class in BDM_supportClasses.h/cpp

I have to change some stuff there for 0.94 anyways, so I'd rather go over that on my own.

We can discuss here whether it is beneficial to add RBF creation in Armory. If so (I believe it is a feature Armory should have), and you would like to keep contributing on RBF, please update the GUI to allow for the creation and replacement of RBF transactions.

**Comment by achow101** [comment]
I don't know if it would necessarily be beneficial to allow for the creation and replacement of RBF transactions, but it may be useful at the very least to boost the fees if they are too low.

I'll add in some stuff in the GUI for that then.

**Comment by goatpig** [comment]
The usefulness of that feature within Armory's scope is up for discussion. Maybe we should take this to the forum first and have other participate. I believe it fits the overall theme of Armory which is to allow for a high level of control on Bitcoin transacting.

**Comment by achow101** [comment]
Sure, let's ask the forum (BTW, I'm knightdk on the forum)

Maybe creating RBF transactions should be something that is only available in expert mode?

**Comment by goatpig** [comment]
Ill create a thread.

**Pull request merged**
