### PR TITLE
Fix release build hang

### PR DESCRIPTION
**Pull request by pavel-kokolemin**

### CODE REVIEW

**Comment by goatpig** [comment]
What is this change for? Why remove the assertion, it's inactive in release builds and a sanity check in debug builds.

**Comment by pavel-kokolemin** [comment]
It's in `btc_privkey_gen`, in release builds it loops forever.

**Comment by goatpig** [comment]
What controls the loop is the priv key check, not the assert. I don't understand what the assert has to do loop lifetime. What compiler is this on?

**Comment by pavel-kokolemin** [comment]
```
void btc_privkey_gen(btc_key* privkey)
{
    do {
        assert(btc_random_bytes(privkey->privkey, BTC_ECKEY_PKEY_LENGTH, 0));
    } while (btc_ecc_verify_privatekey(privkey->privkey) == 0);
}
```

It's in `btc_privkey_gen` function, which should generate private key (I suppose).
So it first generates key with `btc_random_bytes` and then verifies it with `btc_ecc_verify_privatekey`. If check fails new random bytes should be generated. In release build `assert` is removed and it loops forever (when data is filled with 0 and always is same). `btc_ecc_verify_privatekey` returns same result.

I was able reproduce problem on both windows and linux (in release builds).
I see that upsteam repo also has same problem:
https://github.com/libbtc/libbtc/blob/master/src/ecc_key.c#L66
And here is one bug report about abusing `assert` (not specific to this bug trough): https://github.com/libbtc/libbtc/issues/148

**Comment by goatpig** [comment]
The assert macro should result in a no-op in release mode. Check the compilers you are using lead to that.

Again, the loop is controlled by the privkey check, not the PRNG call. This assert is only there to fire in debug builds as a sanity check, and needs to be there for debug builds. Removing that assert should have no effect on the privkey check passing, whether in debug or release. If you are experiencing infinite loops in this code in release, it means the PRNG is busted.

Consider the following: if this assert in release mode had an effect, the caller thread would crash (and most likely the process with it), as the PRNG fails to complete properly. It is very unlikely the PRNG can spit valid random bytes that are consistently >= F, to permanently pass the assert yet fail the privkey check.

You're better off investigating the behavior of btc_ecc_verify_privatekey.

**Comment by sergey-chernikov** [comment]
As a maintainer of https://github.com/libbtc/libbtc/pull/92 I tend to agree with Pavel - this is a bug, and it's already fixed there (among several others by @Ation) - Jonas wrongly implies that code inside `assert()` will be executed in release build, which is actually not the case.
We can close this PR and you'd better merge the latest code from https://github.com/libbtc/libbtc/pull/92, which contains other fixes, too.

**Comment by goatpig** [comment]
Sergey's version is significantly better indeed.

**Pull request closed without merging**
