### PR TITLE
Enable Google Protocol Buffers (protobuf) compilation under *NIX systems

### PR DESCRIPTION
**Pull request by droark**
At the moment, there are two outstanding issues.

- There seems to be some sort of Autotools issue that causes issues when compiling via the typical Autotools route. For now, use a similar system to what libwebsockets uses in order to properly compile protobuf. This may be altered slightly later to use CMake, which seems to be preferred by Google anyway.
- Test/Benchmark code isn't compiled. This will be addressed later.

### CODE REVIEW

**Comment by droark** [comment]
Accidentally closed when I had a hard reset. Will reopen in a bit once a couple of files have been straightened out.

**Comment by andre-amorim** [comment]
I am having a **diff**iculties to understand the alphabet issue, is it possible to clarify in more details ?

**Comment by andre-amorim** [comment]
In the end of the day we are just flicking switches, in general when I asked questions about programming language such as web applications (sorry I am not a language specialist) I think more as a maker, less as a coder

**Comment by droark** [comment]
I'm sorry. Maybe it's a language issue but I still have no idea what you're talking about. I never said anything about "the alphabet issue," and I don't know what that means.

**Pull request closed without merging**
