### PR TITLE
Improve Python 3 Compatibility.

### PR DESCRIPTION
**Pull request by jameshilliard**

### CODE REVIEW

**Comment by droark** [comment]
utACK

Looked the code over. As best I can tell, all the changes are sane and reasonable.

**Comment by goatpig** [comment]
__future__ is one of those libraries that allows for both py2 and py3 to run the same codebase right? Is this the route you're taking or will this not run with py2 anymore once you're done?

**Comment by jameshilliard** [comment]
Yes, however I'm not actually using it here at the moment, I'm just using the `__future__` imports built into python.

**Comment by jameshilliard** [comment]
So to clarify I am planning on using the following multi-stage migration strategy.

1. Make changes improving compatibility with Python 3 without breaking Python 2 support until feature parity is achieved and there are no known Python 3 issues. This stage should be minimally invasive as changes should be tested under both the Python 2 and Python 3 interpreter to ensure behavior is the same and that no regressions are introduced. By first converting to a universal python style we can gradually convert/test the codebase against python 2 and python 3 without having to freeze all development. I do not plan to migrate qt4 to qt5 during this stage.
2. Drop Python 2 support as running under Python 3 should have full parity with Python 2 at this stage.
3. Make any changes to Armory that will reduce the qt4 to qt5 migration diff without breaking qt4.
4. Replace qt4 with qt5(via the python pyside2 library) as a flag day change.

This strategy should minimize the individual pull request diff sizes and flag day changes needed for the migration by allowing iterative development throughout most of the process(aside from the qt4 to qt5 migration which will be at least somewhat a flag day change due to the difficulty in supporting both at the same time).

**Comment by goatpig** [comment]
cherry picked into dev, closing.

**Pull request closed without merging**
