### PR TITLE
[trivial] Remove duplicate MAC OS check from ArmoryQt

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by droark** [comment]
Hello. I put that check there. It was required only for OS X, so I didn't feel the need to risk wrecking the Windows and Linux builds. If this code is pulled, it needs to be checked to make sure the fonts and such don't look screwy.

**Comment by goatpig** [comment]
Not feeling too comfortable with this, please test it before hand.

**Comment by fanquake** [comment]
The check is still there, I've just removed the duplicate. i.e

```
# Load our framework with OS X-specific code.
if OS_MACOSX:
   import ArmoryMac
if OS_MACOSX:
   QApplication.setDesktopSettingsAware(False)
```

to 

```
# Load our framework with OS X-specific code.
if OS_MACOSX:
   import ArmoryMac
   QApplication.setDesktopSettingsAware(False)
```

**Comment by droark** [comment]
Ahhh, I see now. That's fine.

**Pull request merged**
