### PR TITLE
OS X fixes

### PR DESCRIPTION
**Pull request by droark**
Fixes after compiling on a fresh OS X 10.11 install.

### CODE REVIEW

**Comment by goatpig** [comment]
Is this ready? Also, what's the state on shadow warning cleanup PR?

**Comment by droark** [comment]
@goatpig - Yep, it's ready to go. There are other bugs but this will allow those using OSX 10.11 and Xcode 7 to build Armory. (As mentioned before, newer combos won't work.)

Regarding the shadow warning cleanup, I need to rebuild and check the results. I would like to check in a small Autotools change to support easily enabling the flag and disabling it for third party packages. (Crypto++ in particular is an annoying offender that clogs up the build log.) After that, once I do a build, it'll be ready. I hope to get to it by the end of the week.

**Comment by droark** [comment]
@goatpig - Uggh. I thought this was ready but a last-minute change I needed to make undid a couple of things. Will report back when I'm ready to go.

**Comment by droark** [comment]
@goatpig - Ready to go again, for real this time!

**Pull request merged**
