### PR TITLE
* Add multiples options to specify the IP address of bind or connect …

### PR DESCRIPTION
**Pull request by flopraden**
Permit to specify host IP to connect or bind to: 

  + RPC call to bitcoind
  + PEERs connect to bitcoind
  + Armory RPC bind
  + Armory InterProcess communication through TCP

### CODE REVIEW

**Comment by goatpig** [comment]
Not merging this.

First of all, PRs should be based on dev, not master. 

Second, in dev, the Python node P2P code has been abandoned and the feature replaced in the C++ ArmoryDB binary.

Lastly, Armory is currently built to rely on a local node. There are plans to allow remote nodes, but it requires certain improvements to take place in Bitcoin Core first, and it is not as simple as pointing the node code to another IP. 

Armory currently accesses raw blockchain data directly on disk. To support remote nodes, that data needs to be fetched through the P2P layer. This will require a substantial rewrite of certain DB key elements.

**Comment by flopraden** [comment]
I have not read the entire code but why armoryd/armoryQt is listed as a peer in bitcoind info if it just read block from harddisk ?
In my setup, nothing in binded to localhost so I need to connect to a specific ip address, even if it's on the same host

**Comment by achow101** [comment]
It does both, it connects as both a peer and reads from the disk. It
reads from the disk to get transactions once they are confirmed. It
connects as a peer to get unconfirmed transactions.

**Comment by flopraden** [comment]
So without the --satoshi-host option, the armoryd server could not connect to a bitcoind server started with a -bind=IP  (or -whitebind in case on tor only setup with no bind)

**Comment by flopraden** [comment]
It could be break into multiple PR : 
+ Armory RPC bind is usefull to permit others host to communicate with armory daemon
+ PEERs connection to bitcoind is needed to permit to an already running bitcoind process with a specific IP

I'm not sure the 2 others is usefull

**Comment by goatpig** [comment]
1) Pretty sure I already merged a PR to allow binding armoryd RPC interface. Again, check the state of dev, not master.

2) Not until Core implements BIP151 + auth scheme. Armory ultimately trusts its supporting node, not gonna allow remote connections without a proper secure channel first.

**Comment by ashinigami** [comment]
That is unfortunate. There are plenty of circumstances where someone would want a full-featured Bitcoin wallet like Armory but without operating a full bitcoin node on the same machine. If your server is on your LAN etc it wouldn't mandate BIP151 first - it would be sufficient to just warn the user of the risks in the flag description. The bitcoin blockchain can be mounted via NFS etc...
This patch works on 0.94.1 still, so I guess we have to stick to this version if we want this behaviour.

**Comment by flopraden** [comment]
That's exactly my setup : NFS & lan settings. the change is quite simple so it would be easy to backport to dev.
A warning message could be set (as @ashinigami implemented, if I saw right in your branch) if some 127.0.0.1 option are changed

**Comment by goatpig** [comment]
1) 0.95 allows separation of the server and client. In this case, you have to run one ArmoryDB server against a local Bitcoin Node, and can connect remotely with any amount of light weight clients.

2) I'll be implementing BIP151 style encryption with auth for the encrypting client to server communications, so that's not only for the scope of remote Nodes.

3) Remote nodes will be allowed through fetching block data over the P2P layer (instead of expecting the data on disk). With BIP151, it will complete component isolation. However that feature isn't mandatory for your setup (remote clients). 0.95 fulfills that.

**Pull request closed without merging**
