### PR TITLE
Goatpig rpmbuild

### PR DESCRIPTION
**Pull request by Rudd-O**

### CODE REVIEW

**Comment by goatpig** [comment]
Can you rebase your PRs off of the current dev branch? Too much has changed vs master, will most likely conflict.

**Comment by Rudd-O** [comment]
I will try, but I'm pretty sure this one applies almost 100% cleanly.  Give me a few minutes.

**Comment by Rudd-O** [comment]
Well, shit, this doesn't work, because Github doesn't let me alter the source and target branches for the PR.

**Comment by Rudd-O** [comment]
But I was right, the thing applied cleanly.

**Comment by Rudd-O** [comment]
This is crap, I'm going to have to rebase all my requests.

**Pull request closed without merging**
