### PR TITLE
Translation documentation and translation resources

### PR DESCRIPTION
**Pull request by achow101**
Added documentation for translations.

Updated the resources for translations from Transifex

### CODE REVIEW

**Comment by goatpig** [comment]
Merged manually. Github somehow didn't notice that. Closing this.

**Comment by achow101** [comment]
That's because I made a typo fix which I force pushed just before you merged.

**Comment by goatpig** [comment]
oups. can you add the typo fix to the ati removal pr instead?

**Comment by achow101** [comment]
Ok.

**Pull request closed without merging**
