### PR TITLE
Fully remove remaining torrent code

### PR DESCRIPTION
**Pull request by fanquake**
First pass at removing all the remaining torrent code. This still needs more testing.

### CODE REVIEW

**Comment by goatpig** [comment]
Too many changes for this release. I'll go over this PR after 0.94 is out.

**Comment by fanquake** [comment]
@goatpig did you still want to review this? I can rebase if needed but it doesn't look like there are any conflicts.

**Comment by goatpig** [comment]
Once 0.95 goes into testing ill start merging PRs. Rebase on dev if you'd like

**Comment by fanquake** [comment]
Rebased on dev

**Comment by fanquake** [comment]
Rebased on dev

**Comment by fanquake** [comment]
Are you still planning on merging PRs now that we're in the 0.95 testing phase?

**Comment by goatpig** [comment]
Yes. Please rebase on dev one last time, going over PRs this week.

**Pull request closed without merging**
