### PR TITLE
Remove AppNope and webkit from OSX build script

### PR DESCRIPTION
**Pull request by fanquake**
Update libpng to 1.6.24
Remove the no-longer used git code

@droark can you have a look here?

### CODE REVIEW

**Comment by droark** [comment]
Changes look fine at a glance. There's some crud in there from long ago that I've left in just in case. I seriously doubt we'll ever need that stuff, though.

I do have one question. Why did you add the new Qt config params? Just curious where they came from. I'm sure they're fine.

**Comment by fanquake** [comment]
We use similar params for [Qt 4.6](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt46.mk) in bitcoins depends system. I was considering adding some more, as we could cull quite a bit.

What's your thoughts on moving to Qt5? Is that something we should be looking at now? [Qt 5.6.1](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk) in depends should give some insight into how it will need to be compiled.

**Comment by droark** [comment]
Thanks. I think the config changes are fine. I want to say there's a reason Webkit is built but I'm probably wrong. I can always re-enable it if it's needed.

Regarding Qt5, I'd love to upgrade to it. Unfortunately, for various reasons, the upgrade has to go hand-in-hand with a Python 3 upgrade. ATI was working on this and even had a functioning prototype of sorts. Unfortunately, that code can't be used. Goatpig would basically have to stop all Python development for 2-4 weeks while he or somebody else did the conversion (relatively straightforward, if error-prone, with the right scripts) and then meticulously went through the code to catch the many mistakes made by the conversion scripts. Then, there would be testing of the new code (I don't think the OS X prototype ever fully got off the ground) and other hurdles to clear. Not impossible, just very time-consuming. (At least, AFAIK, all the libraries Armory relies on now support Py3, or at least the bits Armory uses in cases such as Twisted.)

**Comment by goatpig** [comment]
Qt5 will happen eventually but it isn't a priority, more like a quality of life change.

**Comment by goatpig** [comment]
Is this ready to merge?

**Comment by fanquake** [comment]
Yes it should be ok to merge.

**Comment by goatpig** [comment]
Ok waiting on @droark ACK and I'll merge

**Comment by droark** [comment]
ACK

Not a fan of some of the comments being removed but I'll live. Looks fine otherwise.

**Pull request merged**
