### PR TITLE
fixes missing executable on compile time on Ubuntu

### PR DESCRIPTION
**Pull request by t0rrant**
Add installation instruction for qttools5-dev-tools which installs:

    /usr/lib/i386-linux-gnu/qt5/bin/lrelease

needed by Makefile

### CODE REVIEW

**Comment by goatpig** [comment]
Armory uses qt4, lrelease can be found in the following dependency: python-qt4

**Comment by t0rrant** [comment]
on Ubuntu 16.04 that doesn't seem to be the case:

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial

qttools5-dev-tools uninstalled:

> $ apt-cache policy qttools5-dev-tools
qttools5-dev-tools:
  Installed: (none)
  Candidate: 5.5.1-3build1
  Version Table:
     5.5.1-3build1 500
        500 http://........archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

make gives an error:
> $ ./make
> (........)
> cp cppForSwig/ArmoryDB ./ArmoryDB
> cp cppForSwig/CppBlockUtils.py ./CppBlockUtils.py
> cp cppForSwig/.libs/libCppBlockUtils.so ./_CppBlockUtils.so
> lrelease lang/*.ts
> lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory
> Makefile:831: recipe for target 'lrelease' failed
> make[1]: *** [lrelease] Error 1
> make[1]: Leaving directory '......../BitcoinArmory'
> Makefile:413: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
> (........)

python-qt4 is installed, checking which files are made available by the package:

> $  dpkg -L python-qt4
> /.
> /usr
> /usr/share
> /usr/share/doc
> /usr/share/doc/python-qt4
> /usr/share/doc/python-qt4/THANKS
> /usr/share/doc/python-qt4/copyright
> /usr/share/doc/python-qt4/changelog.Debian.gz
> /usr/lib
> /usr/lib/python2.7
> /usr/lib/python2.7/dist-packages
> /usr/lib/python2.7/dist-packages/PyQt4
> /usr/lib/python2.7/dist-packages/PyQt4/QtXml.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtHelp.so
> /usr/lib/python2.7/dist-packages/PyQt4/uic
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/qtproxies.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/proxy_metaclass.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/compiler.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/indenter.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/misc.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/qobjectcreator.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/__init__.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Loader
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/qobjectcreator.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/__init__.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/driver.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/invoke.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/ascii_upper.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/proxy_base.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/load_plugin.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/as_string.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/string_io.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/__init__.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/properties.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/pyuic.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/phonon.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qtwebkit.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qtdeclarative.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/.noinit
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qaxcontainer.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qscintilla.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/icon_cache.py
> /usr/lib/python2.7/dist-packages/PyQt4/uic/exceptions.py
> /usr/lib/python2.7/dist-packages/PyQt4/QtTest.so
> /usr/lib/python2.7/dist-packages/PyQt4/Qt.so
> /usr/lib/python2.7/dist-packages/PyQt4/pyqtconfig.py
> /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtXmlPatterns.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtScriptTools.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtWebKit.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtDBus.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtDeclarative.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtDesigner.so
> /usr/lib/python2.7/dist-packages/PyQt4/__init__.py
> /usr/lib/python2.7/dist-packages/PyQt4/QtNetwork.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtScript.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtSvg.so
> /usr/lib/python2.7/dist-packages/PyQt4/QtAssistant.so
> /usr/lib/x86_64-linux-gnu
> /usr/lib/x86_64-linux-gnu/qt4
> /usr/lib/x86_64-linux-gnu/qt4/plugins
> /usr/lib/x86_64-linux-gnu/qt4/plugins/designer
> /usr/lib/x86_64-linux-gnu/qt4/plugins/designer/libpyqt4.so

**Comment by UncleHunto** [comment]
You are probably having this problem, because in Ubuntu the qt4 version of lrelease is named something else. For instance in Arch Linux it is named "lrelease-qt4".  you can remedy this by first finding out what the qt4 version is named in Ubuntu. I would do this by searching the /usr/bin directory for all programs/links to programs which contain "lrelease" in the name. This could be accomplished by running the following command in your terminal:  
`find "/usr/bin" -mindepth 1 -maxdepth 1 -name "*lrelease*" -printf '%f\n'`
Look for a program with something like qt4 in the name.  Then edit the Armory makefile.am and replace all occurrences of "lrelease" with the name of Ubuntu's qt-4 lrelease. This can be done with the following command:
`sed -i -- 's/lrelease/lrelease-qt4/g' "path/to/armory/repo/Makefile.am"`
But of course replace "path/to/armory/repo" with the repo's location on your computer, and replace "lrelease-qt4" with the programs name on your computer.

**Comment by t0rrant** [comment]
Indeed I already had lrelease, although it was named lrelease-qt4,  whereas after installing qttools5-dev-tools I have /usr/bin/lrelease which points to /usr/bin/qtchooser:

> ~$ ls -l /usr/bin | grep lrelease 
> lrwxrwxrwx 1 root   root           9 Dez  9  2015 lrelease -> qtchooser
> lrwxrwxrwx 1 root   root          40 Abr  5  2016 lrelease-qt4 -> ../lib/x86_64-linux-gnu/qt4/bin/lrelease

still, using one lrelease or the other seems to have the same effect.

**Pull request closed without merging**
