### PR TITLE
Manual Entropy

### PR DESCRIPTION
**Pull request by jimmysong**
Added a way to add manual entropy to wallet creation.

It uses shuffling a deck of 52 cards and inputting that into the creation dialog to add entropy.

### CODE REVIEW

**Comment by jimmysong** [comment]
Thanks to @jonvaage for providing the card icons.

**Comment by jonvaage** [comment]
Cool!

I just thought of another possible modification: I remember seeing a line
on the GUI showing the amount of entropy as an integer. What do you think
of rounding that down to the nearest power of 2 since most documentation on
entropy is in terms of bits?

**Comment by jimmysong** [comment]
That's a good idea. Maybe express it in terms of bits of entropy generated.

**Comment by jonvaage** [comment]
Yeah, exactly. I think the bitcoin private key space is just shy of 256
bits and a thoroughly shuffled deck has around 225 bits of entropy IIRC.

**Comment by goatpig** [comment]
Manually merged into testing. Closing the PR.

**Pull request closed without merging**
