### PR TITLE
.gitignore ArmoryDB

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by droark** [comment]
Hi. If it's okay, can the following items be added? They're not related to ArmoryDB but would be good to add. I can add them separately if it's desired to keep everything separate. Thanks.

/cppForSwig/cryptopp/*.a
/cppForSwig/gtest/ContainerTests
/cppForSwig/gtest/CppBlockUtilsTests
/cppForSwig/gtest/*.txt
/cppForSwig/gtest/*.a
/cppForSwig/gtest/*.out.*
/cppForSwig/gtest/blkfiletest/*
/cppForSwig/gtest/ContainerTests.dSYM/*
/cppForSwig/gtest/CppBlockUtilsTests.dSYM/*

**Comment by fanquake** [comment]
@droark Updated with your ignores.

**Comment by droark** [comment]
Thanks. If you're feeling ambitious, cppForSwig/gtest/lbtestdir/.gitignore also needs to be updated. I'm seeing the following files there. I can update it if you wish. No pressure. :)

blkdata
blkdata-lock
headers
headers-lock
history
history-lock
ssh
ssh-lock
stxo
stxo-lock
subssh
subssh-lock
txfilters
txfilters-lock
txhints
txhints-lock
zeroconf
zeroconf-lock

**Comment by fanquake** [comment]
@droark done.

**Comment by droark** [comment]
Hi. The second commit is actually a bit off. The following lines have been corrected.

/cppForSwig/cryptopp/*.a
/cppForSwig/gtest/*.txt
/cppForSwig/gtest/*.a
/cppForSwig/gtest/*.out.*

**Comment by fanquake** [comment]
I've made the corrections.

**Comment by droark** [comment]
ACK

Excellent. I think that covers everything I'm seeing on my end. Thanks for doing this. :)

**Pull request merged**
